---
title: "Parte 1 - Análise do Dataset"
author: "Adriana Matsubara, Bruno Aquino, Rafael Bueno, Vinicius Scimioni"
date: "21 de maio de 2018"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Análise Táxi NY

<p>
Descrição do exercício
</p>
Carregar as "libraries" a serem utilizadas:

```{r}
library(magrittr) # quando der problema com o "%>%"
library('dplyr') # selecao e filtro de dados
library('geosphere') # localizacao geoespacial
library(lubridate) # datas, funções hour, month, wday
library(plotly) # plot dos gráficos
library(knitr) # usada pelo plotly
library(dummies) # cria colunas binárias para variáveis categóricas
library(scales) # normaliza dados rescalando para float de 0 a 1
library(randomForest) # cria rede neural para criar regressão de tempo de viagem
source('preprocessing.R')
```


## 1 - Entendimento / Descrição do Dataset

Carregar os datasets

```{r include=FALSE}
train = read_csv("data/train.csv")
test = read_csv("data/test.csv")
```

Verificar se existem nulos

```{r}
sum(is.na(train))
sum(is.na(test))
```

Summary das tabelas

```{r}
summary(train)
```

```{r}
summary(test)
```

Variáveis de Data

```{r}
train$pickup_hour <- hour(train$pickup_datetime)
train$pickup_week <- week(train$pickup_datetime)
train$pickup_month <- month(train$pickup_datetime)
train$pickup_weekdays <- weekdays(train$pickup_datetime)
train$pickup_weekend <- ifelse(train$pickup_weekdays==1 | train$pickup_weekdays==7,"Weekend","not-Weekend")

train = as.data.table(train)

train[,pickup_datetime:=as.Date(pickup_datetime)]
train[,dropoff_datetime:=as.Date(dropoff_datetime)]

train[,":="(
   pickup_yday=yday(pickup_datetime)
  ,pickup_mday=mday(pickup_datetime)
)]
```


```{r}

```













